service: headless-chrome-example

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-west-2

package:
  exclude:
    - ./**
  include:
    - node_modules/**
    - headless-chrome/**
    - handler.js
    - buffer-polyfill.js

functions:
  mimir:
    memorySize: 1024
    timeout: 30
    handler: handler.run
